version: '3'
services:
    reader:
        build:
            context: .
            dockerfile: reader.dockerfile
        image: '764201992552.dkr.ecr.us-east-1.amazonaws.com/rivitt-serial-reader'
        container_name: reader
        env_file:
            - general.env
        devices:
            - "/dev/ttyS0:/dev/ttyS0"
            - "/dev/ttyS1:/dev/ttyS1"
            - "/dev/ttyS2:/dev/ttyS2"
            - "/dev/ttyS3:/dev/ttyS3"
            - "/dev/ttyS4:/dev/ttyS4"
        environment:
            - HOSTNAME="${HOSTNAME}"
        restart: always
    producer:
        build:
            context: .
            dockerfile: producer.dockerfile
        image: '764201992552.dkr.ecr.us-east-1.amazonaws.com/rivitt-serial-producer'
        container_name: 'producer'
        env_file:
            - general.env
        environment:
            - HOSTNAME="${HOSTNAME}"
        restart: always
