version: '3'
services:
    reader:
        build:
            context: .
            dockerfile: reader.dockerfile
        image: reader
        container_name: 'reader'
        env_file:
            - general.env
        devices:
            - "/dev/ttyS0:/dev/ttyS0"
        environment:
            - HOSTNAME="${HOSTNAME}"
        restart: always
        depends_on:
            - mongodb
    producer:
        build:
            context: .
            dockerfile: producer.dockerfile
        image: producer
        container_name: 'producer'
        env_file:
            - general.env
        restart: always
        depends_on:
            - mongodb
